# -*- coding: utf-8 -*-
"""auto-email-file-dispatcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZY5pzReSDxsVuOCqrmuACnAyH1pzV_K
"""

import pandas as pd
import os
import re
import zipfile
import smtplib
import time
import random
from email.message import EmailMessage

EMAIL = "moazzamkk13@gmail.com"
APP_PASSWORD = "YOUR_APP_PASSWORD_HERE"

NAME_COLUMN = "Full Name"
EMAIL_COLUMN = "Email Address"
ID_COLUMN = "ID"

EMAIL_SUBJECT = "Important Document"

EMAIL_BODY = """
Dear {name},

Please find your attached document.

Regards,
Automated System
"""

DELAY_MIN = 5
DELAY_MAX = 10

def clean_text(text):
    if pd.isna(text):
        return None
    text = str(text).strip().replace("\u00a0", " ")
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r'[\/:*?"<>|]', "", text)
    return text.title()

def extract_id(text):
    if pd.isna(text):
        return None
    match = re.findall(r"\d{3,6}", str(text))
    return match[-1] if match else None

def parse_file(filename):
    base = os.path.splitext(filename)[0]
    ids = re.findall(r"\d{3,6}", base)
    file_id = ids[-1] if ids else None
    name = re.sub(r"_?\d{3,6}_?", " ", base)
    name = clean_text(name)
    return name, file_id

csv_file = input("CSV path: ")
zip_file = input("ZIP file path: ")

df = pd.read_csv(csv_file, engine="python", encoding="utf-8", on_bad_lines="skip")
df.columns = df.columns.str.strip()
df = df.dropna(subset=[NAME_COLUMN, EMAIL_COLUMN])

FOLDER = "files"
os.makedirs(FOLDER, exist_ok=True)

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall(FOLDER)

files_by_id = {}
files_by_name = {}

for file in os.listdir(FOLDER):
    path = os.path.join(FOLDER, file)
    if os.path.isfile(path):
        name, file_id = parse_file(file)

        if file_id:
            files_by_id[file_id] = path
        if name:
            files_by_name[name] = path

server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(EMAIL, APP_PASSWORD)

sent, missing, failed = [], [], []

for _, row in df.iterrows():
    name = clean_text(row[NAME_COLUMN])
    email = row[EMAIL_COLUMN]
    file_id = extract_id(row.get(ID_COLUMN))

    file_path = None

    if file_id and file_id in files_by_id:
        file_path = files_by_id[file_id]
    elif name in files_by_name:
        file_path = files_by_name[name]

    if not file_path:
        missing.append(name)
        continue

    try:
        msg = EmailMessage()
        msg["Subject"] = EMAIL_SUBJECT
        msg["From"] = EMAIL
        msg["To"] = email
        msg.set_content(EMAIL_BODY.format(name=name))

        with open(file_path, "rb") as f:
            msg.add_attachment(
                f.read(),
                maintype="application",
                subtype="octet-stream",
                filename=os.path.basename(file_path)
            )

        server.send_message(msg)

        sent.append(name)
        print("Sent:", name)

        time.sleep(random.randint(DELAY_MIN, DELAY_MAX))

    except Exception as e:
        failed.append(name)
        print("Failed:", name, e)

server.quit()

report = pd.DataFrame({
    "Sent": pd.Series(sent),
    "Missing": pd.Series(missing),
    "Failed": pd.Series(failed)
})

report.to_csv("report.csv", index=False)

print("DONE")